### ISSUE TITLE
create_cohesive_elements(mesh, 3)

### ISSUE THREAD

**Issue by mumayy** [KristofferC/Phon#25]
create_cohesive_elements(mesh, 3) gives error. 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\.....\Phon-master\phon\mesh_tools\create_cohesive_elements.py", line 62, in create_cohesive_elements
    for element_set_name in mesh.element_sets.keys():
RuntimeError: OrderedDict mutated during iteration

**Comment by shuaizhou001** [comment]
It is your Python version problem.
You should change some lines of the codes.

**Comment by mumayy** [comment]
Thank you for your answer, but which parts should I change?
